---

- hosts: client
  become: yes 
  tasks:
   
    - name: Install NTP
      apt: package=ntp state=present update_cache=yes
      tags: ntp
  
    - name: Copy over the NTP configuration
      template: src=client/ntp.conf dest=/etc/ntp.conf
      notify:
        - restart ntp
      tags: ntp
 
    - name: Make sure NTP is started up
      service: name=ntp state=started enabled=yes
      tags: ntp
  handlers:
    - name: restart ntp
      service: name=ntp state=restarted
  

- hosts: server
  become: yes
  tasks:
    - name: Install NTP
      apt: package=ntp state=present update_cache=yes
      tags: ntp
  
    - name: Copy over the NTP configuration
      template: src=server/ntp.conf dest=/etc/ntp.conf
      notify:
        - restart ntp
      tags: ntp
 
    - name: Make sure NTP is started up
      service: name=ntp state=started enabled=yes
      tags: ntp


  handlers:
    - name: restart ntp
      service: name=ntp state=restarted
  

